---
  name: "my graph name"
  sources: 
    - "ec2"
  edges: 
    -
      from_shape: "egg"
      from_color: "orange"
      from: "ec2_instance_id"
      to: "ec2_security_groups-group_name"
      to_shape: "triangle"
      to_color: "cyan"
    -
      from: "ec2_vpc_id"
      to: "ec2_instance_id"
